name: dio_pretty_logger
description: "A pretty-printing Dio interceptor for debugging HTTP requests and responses."
version: 2.0.0
homepage: https://github.com/deepak07082/dio_pretty_logger.git
repository: https://github.com/deepak07082/dio_pretty_logger.git
issue_tracker: https://github.com/deepak07082/dio_pretty_logger/issues

topics:
  - dio
  - logger
  - pretty
  - interceptor
  - networking

environment:
  sdk: ^3.8.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
